package com.arcanelens.network.packet;

public enum SkillType
{
    MANA_BOOST,
    COOLDOWN_REDUCTION,
    COST_REDUCTION,
    POCKET_DIMENSION,
    POCKET_DIMENSION_EXPANSION,
    STORAGE_SYSTEM,
    STORAGE_NETWORK_EXPANSION,
    ARCANE_ASSEMBLER,
    ASSEMBLER_SPEED,
    ASSEMBLER_FUEL_EFFICIENCY,
    OVERLOAD_RITUAL,
    WARPED_ATTUNEMENT
}
